# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

on:
  schedule:
    # setiap 1 jam
    - cron: "0 */1 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ✅ Checkout repo
      - uses: actions/checkout@v4

      # ✅ Generate snake GIF & SVG
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Said-labs
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # ✅ Deploy langsung ke branch output (tanpa push manual)
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
